### ISSUE TITLE
Infinite loop with links when validating start and end dates

### ISSUE THREAD

**Issue by T-Roth** [deulos/vue-daval#17]
Building on my previous [question ](https://github.com/deulos/vue-daval/issues/16#issuecomment-712529327) when validating start and end dates.  I tried using Links but I see no way to not end up in an infinite loop since both the start and end dates need Links back to each other.  

Do you have a way to handle this scenario?  or can Links be updated to detect the circular paths and only run once?

**Comment by deulos** [comment]
No, unfortunately 2 linked fields will loop because there is no way to know how or when links should not call the other and I answered your other issue.

A very handy way to overpass this circumstance is creating a watcher that forces the revalidation of the other field, in each other, so whenever one field changes will just trigger the validation of the other without entering in any loop :)
